apiVersion: v1
kind: Service
metadata: 
  name: order-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path:   '/metrics'
    prometheus.io/port:   '3002'
spec: 
  selector: 
    app: order-service
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 3002
  type: NodePort